name: My First GitHub Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install noe modules
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Sets the Vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"projectId":"prj_710RMviPvvJ4E0WctjApjW2KpyOO","orgId":"Q5gMqszqF4BXPCCCxPkXPxYX"} > project.json'
      - name: Deploying the project
        run: npm run deploy
      - name: Setup Finish
        run: echo "Yaay! Janely!!"
